.bd B 3
.TH abs6x 1 "Dec 07, 2012" "TI Tools" "TI Code Generation Tools"
.SH NAME
abs6x - Absolute Lister
.SH SYNOPSIS
.B abs6x
[
.I options
] [
.I file(s)
]
.SH DESCRIPTION
The absolute lister is a debugging tool that accepts linked object files as input and creates .abs files as output.  These .abs files can be assembled to produce a listing that shows the absolute addresses of object code.
.SH OPTIONS
The following options are accepted by this tool:
.SS Options:
.SS
.TP
-EA=ext
Change default filename extension for assembly files [Same as -ea]
.TP
-ea=ext
Change default filename extension for assembly files [Same as -EA]
.TP
-EC=ext
Change default filename extension for C source files [Same as -ec]
.TP
-ec=ext
Change default filename extension for C source files [Same as -EC]
.TP
-EH=ext
Change default filename extension for header files [Same as -eh]
.TP
-eh=ext
Change default filename extension for header files [Same as -EH]
.TP
-ep=ext
Change default filename extension for CPP source files [Same as -EP]
.TP
-EP=ext
Change default filename extension for CPP source files [Same as -ep]
.TP
-fs=dir
Specify the ABS output file directory [Same as -FS]
.TP
-FS=dir
Specify the ABS output file directory [Same as -fs]
.TP
-h
Display a help message that includes usage and option information [Same as -H]
.TP
-H
Display a help message that includes usage and option information [Same as -h]
.TP
-pdew
Treat warnings as errors
.TP
-q
Quiet [Same as -Q]
.TP
-Q
Quiet [Same as -q]
.SH EXIT STATUS
The following error values are returned:
.PD 0
.TP 10
.B 0
Successful completion.
.TP
.B >0
Unsuccessful completion; an error occured.
.PD
.SH COPYRIGHT
.TP
Copyright (c) 2012, Texas Instruments, Inc.
