.bd B 3
.TH asm6x 1 "Dec 07, 2012" "TI Tools" "TI Code Generation Tools"
.SH NAME
asm6x - Assembler
.SH SYNOPSIS
.B asm6x
[
.I options
] [
.I file(s)
]
.SH DESCRIPTION
The assembler translates human readable assembly language source files into machine language object files that are used by the linker.  Source files can contain instructions, assembler directives and macro directives.  You can use assembler directives to control various aspects of the assembly process, such as source listing format, data alignment, and section content.  The Assembler should not be invoked directly; it should be invoked via the shell (cl).  For more information on the assembler, see the 
.B Assembly Language Tools User's Guide.

This tool should be invoked via the shell (cl).  See the shell documentation for information on shell options.
.SH COPYRIGHT
.TP
Copyright (c) 2012, Texas Instruments, Inc.
