.bd B 3
.TH cg6x3 1 "Dec 07, 2012" "TI Tools" "TI Code Generation Tools"
.SH NAME
cg6x3 - Code Generator
.SH SYNOPSIS
.B cg6x3
[
.I options
] [
.I file(s)
]
.SH DESCRIPTION
The code generator creates assembly code and debugging information from the internal compiler representation.  The Code Generator should not be invoked directly; it should be invoked via the shell (cl).  For more information on the code generator, see the 
.B Optimizing C Compiler User's Guide.

This tool should be invoked via the shell (cl).  See the shell documentation for information on shell options.
.SH COPYRIGHT
.TP
Copyright (c) 2012, Texas Instruments, Inc.
