.bd B 3
.TH ci6x 1 "Dec 07, 2012" "TI Tools" "TI Code Generation Tools"
.SH NAME
ci6x - Compiler Consultant XML Generator
.SH SYNOPSIS
.B ci6x
[
.I options
] [
.I file(s)
]
.SH DESCRIPTION
Generates XML-formatted compiler hints
.SH OPTIONS
The following options are accepted by this tool:
.SS Options:
.SS
.TP
-h
Print a help message that includes usage and option information.
.TP
-pdew
Treat warnings as errors
.SH EXIT STATUS
The following error values are returned:
.PD 0
.TP 10
.B 0
Successful completion.
.TP
.B >0
Unsuccessful completion; an error occured.
.PD
.SH COPYRIGHT
.TP
Copyright (c) 2012, Texas Instruments, Inc.
