.bd B 3
.TH clt6x 1 "Dec 07, 2012" "TI Tools" "TI Code Generation Tools"
.SH NAME
clt6x - Cache Layout Tool
.SH SYNOPSIS
.B clt6x
[
.I options
] [
.I file(s)
]
.SH DESCRIPTION
Uses profiling information to generate a function ordering that will tend to reduce instruction cache misses.
This tool should be invoked via the shell (cl).  See the shell documentation for information on shell options.
.SH COPYRIGHT
.TP
Copyright (c) 2012, Texas Instruments, Inc.
