.bd B 3
.TH nm6x 1 "Dec 07, 2012" "TI Tools" "TI Code Generation Tools"
.SH NAME
nm6x - Name Utility
.SH SYNOPSIS
.B nm6x
[
.I options
] [
.I file(s)
]
.SH DESCRIPTION
Generates a list of symbol names for an object file or archive
.SH OPTIONS
The following options are accepted by this tool:
.SS Options:
.SS
.TP
-A
List all symbols [Same as -a]
.TP
-a
List all symbols [Same as -A]
.TP
-C
Include C_NULL symbols in listing (COFF only) [Same as -c]
.TP
-c
Include C_NULL symbols in listing (COFF only) [Same as -C]
.TP
-d
Include debug symbols in listing (COFF only) [Same as -D]
.TP
-D
Include debug symbols in listing (COFF only) [Same as -d]
.TP
-F
Prepend file name to each symbol [Same as -f]
.TP
-f
Prepend file name to each symbol [Same as -F]
.TP
-G
List global symbols only [Same as -g]
.TP
-g
List global symbols only [Same as -G]
.TP
-h
Display a help message that includes usage and option information [Same as -H]
.TP
-H
Display a help message that includes usage and option information [Same as -h]
.TP
-l
List more detailed symbol information [Same as -L]
.TP
-L
List more detailed symbol information [Same as -l]
.TP
-n
Sort symbols by value rather than alphabetically [Same as -N]
.TP
-N
Sort symbols by value rather than alphabetically [Same as -n]
.TP
-o=file
Prints the listing to <file> rather than to stdout [Same as -O]
.TP
-O=file
Prints the listing to <file> rather than to stdout [Same as -o]
.TP
-P
Do not sort symbols [Same as -p]
.TP
-p
Do not sort symbols [Same as -P]
.TP
-pdew
Treat warnings as errors
.TP
-Q
Quiet [Same as -q]
.TP
-q
Quiet [Same as -Q]
.TP
-R
Sort symbols in reverse order [Same as -r]
.TP
-r
Sort symbols in reverse order [Same as -R]
.TP
-S
List symbols in the dynamic symbol table (ELF only) [Same as -s]
.TP
-s
List symbols in the dynamic symbol table (ELF only) [Same as -S]
.TP
-T
Include tag info symbols in listing (COFF only) [Same as -t]
.TP
-t
Include tag info symbols in listing (COFF only) [Same as -T]
.TP
-u
List undefined symbols only [Same as -U]
.TP
-U
List undefined symbols only [Same as -u]
.SH EXIT STATUS
The following error values are returned:
.PD 0
.TP 10
.B 0
Successful completion.
.TP
.B >0
Unsuccessful completion; an error occured.
.PD
.SH COPYRIGHT
.TP
Copyright (c) 2012, Texas Instruments, Inc.
