.bd B 3
.TH opt6x 1 "Dec 07, 2012" "TI Tools" "TI Code Generation Tools"
.SH NAME
opt6x - Optimizer
.SH SYNOPSIS
.B opt6x
[
.I options
] [
.I file(s)
]
.SH DESCRIPTION
The Optimizer optimizes the parser generated internal compiler representation. The Optimizer should not be invoked directly; it should be invoked via the shell (cl).  For more information on the Optimizer, see the 
.B Optimizing C Compiler User's Guide.

This tool should be invoked via the shell (cl).  See the shell documentation for information on shell options.
.SH COPYRIGHT
.TP
Copyright (c) 2012, Texas Instruments, Inc.
