.bd B 3
.TH pdd6x 1 "Dec 07, 2012" "TI Tools" "TI Code Generation Tools"
.SH NAME
pdd6x - Profile Data Decoder
.SH SYNOPSIS
.B pdd6x
[
.I options
] [
.I file(s)
]
.SH DESCRIPTION
Used for profile directed compilation.
This tool should be invoked via the shell (cl).  See the shell documentation for information on shell options.
.SH COPYRIGHT
.TP
Copyright (c) 2012, Texas Instruments, Inc.
