.bd B 3
.TH pprof6x 1 "Dec 07, 2012" "TI Tools" "TI Code Generation Tools"
.SH NAME
pprof6x - Path Profiler
.SH SYNOPSIS
.B pprof6x
[
.I options
] [
.I file(s)
]
.SH DESCRIPTION
Enables source code instrumentation to collect profiling information.  Used for profile directed compilation.
This tool should be invoked via the shell (cl).  See the shell documentation for information on shell options.
.SH COPYRIGHT
.TP
Copyright (c) 2012, Texas Instruments, Inc.
