.bd B 3
.TH xref6x 1 "Dec 07, 2012" "TI Tools" "TI Code Generation Tools"
.SH NAME
xref6x - Cross-reference Utility
.SH SYNOPSIS
.B xref6x
[
.I options
] [
.I file(s)
]
.SH DESCRIPTION
The cross-reference utility is used to generate a cross-reference listing of all known symbols from a user's final linked program (outfile).  This listing can be used to assist in memory arrangement and debugging.
.SH OPTIONS
The following options are accepted by this tool:
.SS Options:
.SS
.TP
-h
Dump a long help message that includes usage and option information. Specify additional option to get long help on that particular option.
.TP
-l=#
Set the number of lines to print on each page before causing a page break and a new header.
.TP
-pdew
Treat warnings as errors
.TP
-q
Quite operation.  Deprecated.
.TP
-t
Truncate the file names to the width of the file name column rather than moving the data to the following line when a file name that is too long for it's column is found.  This option can be enabled for historical behavior.
.SH EXIT STATUS
The following error values are returned:
.PD 0
.TP 10
.B 0
Successful completion.
.TP
.B >0
Unsuccessful completion; an error occured.
.PD
.SH COPYRIGHT
.TP
Copyright (c) 2012, Texas Instruments, Inc.
